### ISSUE TITLE
Side bar issue (toggle on/off button)

### ISSUE THREAD

**Issue by Mara-Li** [chetachiezikeuzor/Yin-and-Yang-Theme#1]
![image](https://user-images.githubusercontent.com/30244939/119971606-77812100-bfb1-11eb-83e6-ffe42ccb81d5.png)
![image](https://user-images.githubusercontent.com/30244939/119971613-794ae480-bfb1-11eb-991a-288e714797ec.png)

The option give a lot of space, so, the name is complety cut with little sidenav.

Also, the information for file (PDF, XLSL) have some problem, as you can see on my screenshot

**Comment by chetachiezikeuzor** [comment]
For the second bit, could you clarify a little more on what the issue with the PDF, XLSL files is?

**Comment by Mara-Li** [comment]
> For the second bit, could you clarify a little more on what the issue with the PDF, XLSL files is? 

Sorry it's XLXS (from Excel). Look the icon, it seems stuck with the sidenav, and expand with it. It doen't against the name file (here it's data)

**Comment by chetachiezikeuzor** [comment]
Ok, I see! I'll add a toggle to turn this off in Style Settings. "Turn off reverse nav file tags" or something of the sort. Thanks!

**Comment by Mara-Li** [comment]
Thank you too :D

**Comment by chetachiezikeuzor** [comment]
I added a toggle to remove the text reversal for attachments and set no folder icons as default (display with toggle on). Hope this clears everything up for you!
