### ISSUE TITLE
[BUG] Strange behavior with cursor after a block citation

### ISSUE THREAD

**Issue by Mara-Li** [chetachiezikeuzor/Yin-and-Yang-Theme#10]
The cursor seems to move away from the active line, which makes it very difficult to know where you are actually writing. 

A picture is worth a thousand words, so here is an explanatory gif.

![06-10-2021_10-15](https://user-images.githubusercontent.com/30244939/121490204-17d53d80-c9d5-11eb-9ec8-45bb81cc0765.gif)

**Comment by chetachiezikeuzor** [comment]
Just pushed an edit for this. I've removed the margin styling (which seems to be causing the cursor issues). Try reinstalling again :)
