### ISSUE TITLE
Formatting Request

### ISSUE THREAD

**Issue by mariowabnig** [chetachiezikeuzor/Yin-and-Yang-Theme#13]
![Screenshot if the indentation lines](https://user-images.githubusercontent.com/85761313/121731413-303a7a80-caf1-11eb-8c9b-e78e16f97776.jpg)
One thing I was wondering about was whether it was possible to change how far down the lines next to indented lines go (the ones I marked with arrows). They are barely visible, I know, and that is my small issue. In Yin and Yang they cover one line only when you reach the most indented line, but I would prefer if they covered it all the way down until it reaches a less indented line as that makes the overview easier I feel like. Maybe I am the only one who prefers it this way, so I am not advocating for a general implementation but it would be amazing if it was changeable in the Style Settings plugin. Also, it would be great to be able to change the lines' color and maybe also their thickness. Thank you very much for your work!

**Comment by chetachiezikeuzor** [comment]
Sorry for the late reply! I'll be sure to add this to my list of new Style Settings features. Thanks!

**Comment by chetachiezikeuzor** [comment]
Ok I've added line indent setting and relationship line thickness setting. You can find them under Yin and Yang Theme > Minimalize Elements > List Elements. 👍
