### ISSUE TITLE
[Bug] [WYSIWYG] Issue with link

### ISSUE THREAD

**Issue by Mara-Li** [chetachiezikeuzor/Yin-and-Yang-Theme#14]
I have a templater note with things between `[ ]`.
When enabling WYSIWYG for the theme (with the style settings), all become transparent/invisible. 

No WYSIWYG : 
![image](https://user-images.githubusercontent.com/30244939/121786518-96420300-cbc0-11eb-8d5c-e1e0ce1b7648.png)

With WYSIWYG : 
![image](https://user-images.githubusercontent.com/30244939/121786531-a2c65b80-cbc0-11eb-9d1f-3052b8676e03.png)

**Comment by chetachiezikeuzor** [comment]
Gahhh! Ok, I’ll fix this right away!

**Comment by chetachiezikeuzor** [comment]
Could you send me a copy of this file? I think that will help a great deal. Thanks!

**Comment by chetachiezikeuzor** [comment]
My latest update should allow for links to be displayed in WYSIWYG mode. Do let me know if you have an issue with it!
