### ISSUE TITLE
Text colours aren't formatted when exporting to pdf from dark mode

### ISSUE THREAD

**Issue by paperboi** [chetachiezikeuzor/Yin-and-Yang-Theme#15]
First of all, thanks for making this beautiful theme. I really appreciate the effort being put into this project and hope to contribute in this small way.

I tried exporting a pdf and found out that the colors of the various elements aren't formatted before being sent for PDF export. Attached a copy of the same file as exported from both light mode and dark mode. Wrt light mode, the various text elements adopt the same colors as within the editor (expected behaviour). But for dark mode, this shouldn't be the case as it would lead to contrast issues and an unreadable document. I suppose we would have to add and assign a separate set of colors for this specific purpose.

[Link to the above-mentioned pdf files](https://www.dropbox.com/sh/1pq5hj9firup0rr/AAAMyVZ7usFgltSL1GZffy5Ka?dl=0)

**Comment by chetachiezikeuzor** [comment]
Oh wow! Ok, I'll look into this today. Is there any way you could send me the .md file (if that's okay with you)?

**Comment by paperboi** [comment]
Sure thing, uploaded it in the same folder as the pdfs above. Hope it helps.

**Comment by chetachiezikeuzor** [comment]
Okay, the issue should be fixed! Try reinstalling the theme.

**Comment by paperboi** [comment]
It worked! Thank you for the quick fix.
