### ISSUE TITLE
Format Tables with code font & Create adjustable code blocks in Style Settings

### ISSUE THREAD

**Issue by s-kyy** [chetachiezikeuzor/Yin-and-Yang-Theme#16]
Hey thank you for making this theme, I've been enjoying it and what you were able to do with the style settings. Great stuff.

I was wondering if you'd be able to fix how the markdown tables align. Right now, they are rendered with the normal text font, but it would be more aligned in editor mode if it renders in a code font instead. 
![image](https://user-images.githubusercontent.com/19920083/122293270-d78a2980-cec4-11eb-9b16-ec4c922370bd.png)

Another aspect I'd like for you to have a way to adjust is adjusting code font size and a way to toggle remove the code block borders. The font is too large and looks jarring (to me) in editor mode when it sits in between text: 
![image](https://user-images.githubusercontent.com/19920083/122293592-29cb4a80-cec5-11eb-982d-3d50709a65dc.png)

Thanks!

In Style Settings: both WYSWIG settings are on (Headings in Editor & Enhanced Editor Typography)
Obsidian Version: v0.12.4
Theme Version: 377df43 (commit hash)

**Comment by chetachiezikeuzor** [comment]
I just had a user bring up this issue and it should be fixed with the latest version! I will be looking into adding these features, thanks!

**Comment by s-kyy** [comment]
Sorry for the late reply. Cheers for being on top of the table issue!

The obsidian font toggle changes the sizes for all fonts together, so while the code font size does shrink, the text font would be too small to read comfortably. 

![image](https://user-images.githubusercontent.com/19920083/122403204-2e871180-cf4c-11eb-96cb-8dec91be9ee0.png)

**Comment by chetachiezikeuzor** [comment]
I guess what I can do is just grant the ability to change code font size in Style Settings. What do you think? I'm actually planning out some new Style Settings features so adding this to the list won't be a problem.

**Comment by s-kyy** [comment]
Yes that's great! Having it as an adjustable setting would make it more customizable for others as well 👍

**Comment by chetachiezikeuzor** [comment]
Code block custom font size has now been added under Yin and Yang Theme > Minimalize Elements > Code Blocks. 👍
