### ISSUE TITLE
Bug: Horizontal Pane Resizing

### ISSUE THREAD

**Issue by zeshalta** [chetachiezikeuzor/Yin-and-Yang-Theme#17]
Hi Chetatchi, 

Updated Yin & Yang to it’s latest version and have lost the ability to resize horizontal/top&bottom panes (there’s nothing to grab to re-adjust). Vertical/side-by-side panes are fine, there’s still a place to grab to resize. 

This is happening on Windows and Mobile.

Ty for the good work!

**Comment by chetachiezikeuzor** [comment]
Sorry about that! The newest push should take care of this. Thanks!

**Comment by zeshalta** [comment]
Awesome! Thank you :D
