### ISSUE TITLE
Bug (Mobile version) Title shown on top of side pane

### ISSUE THREAD

**Issue by TheMathGuyd** [chetachiezikeuzor/Yin-and-Yang-Theme#18]
iPadPro 2018 12.9in

When the screen is split into two panes (top&bottom), the title of the lower pane is shown over the left side bar. 
![638B4E4E-DB41-4399-844B-B0F270306D55](https://user-images.githubusercontent.com/85257386/123270160-a5cd2000-d4cd-11eb-8f32-dc46f7b6066c.jpeg)

Thanks for a beautiful theme ❤️

**Comment by chetachiezikeuzor** [comment]
Hello! Sorry for the late reply but I did add a fix for this in my most recent push! Let me know if you have any issues. 😊
