### ISSUE TITLE
Monochrome emojis

### ISSUE THREAD

**Issue by LaP0573** [chetachiezikeuzor/Yin-and-Yang-Theme#19]
I make heavy use of emojis for my folders (and some files), and I noticed that with the theme active they are appearing as white (or black depending on the theme) monochrome images instead of the colorful emoji (at least in the file explorer and in the suggester).

Example:

![image](https://user-images.githubusercontent.com/9264791/123505841-8a931980-d661-11eb-8b1c-4e9eeb383689.png)

Here the various emojis before the folder names should be the regular, colorful ones.

Would it be possible to add an option for the theme to disable this emojis override and keep the colorful ones?

Cheers!

**Comment by chetachiezikeuzor** [comment]
Ok my most recent push should take care of this! 🤗
