### ISSUE TITLE
Problem with mouse support - cannot click cursor or text select on some  notes in edit view

### ISSUE THREAD

**Issue by danieltomasz** [chetachiezikeuzor/Yin-and-Yang-Theme#2]
Great theme!
After installing the theme I cannot click the cursor on the note. I tested it on the help vault with all plugin disabled.
I could click cursor in different places on some notes, but for example  on the 'Start here' note from obsidian  Help Vault, it doesnt work and could move cursor only by arrow keys and I cannot do text selection in edit mode there.

EDIT: Here was description of unrelated problem

I am on Obsidian 0.12.3 on Linux OS.

**Comment by chetachiezikeuzor** [comment]
Oh no! This sounds awful. Thanks for raising this issue, there must be a mistake I’ve made with the recent update. I’ll look into this as soon as I get back to my laptop!

**Comment by chetachiezikeuzor** [comment]
Hello! I found the issue with the cursor and it should be fixed now. It was 100% an issue with the theme (z-index for scrollbars was the issue) and I apologize for that. Could you reinstall the theme and let me know if the problem persists? I will be adding some major updates (still testing a few things) you'll have to grab a newer update in the next day or two (😅). But for now, the problem should be fixed.

**Comment by danieltomasz** [comment]
It seems to work now! Really nice theme!

**Comment by chetachiezikeuzor** [comment]
Thanks! ʕ•́ᴥ•̀ʔっ♡
