### ISSUE TITLE
Codeblock language not always rendered at the bottom of the screen

### ISSUE THREAD

**Issue by cakechaser** [chetachiezikeuzor/Yin-and-Yang-Theme#20]
First of all thank you for the amazing theme!

I noticed an issue with codeblocks, which happens both in notes and previews.

When a note with a codeblock is opened, hovering over the block shows the block language in the bottom-right corner.
When scrolling down, I would expect this text to stay in the same corner, however it appears to be fixed in place.

**'language-python' displayed correctly in the bottom-right corner:**
![image](https://user-images.githubusercontent.com/16690476/125208789-4d539c00-e29d-11eb-9941-e7943ef42fec.png)

**The name scrolls up with the page:**
![image](https://user-images.githubusercontent.com/16690476/125208774-4167da00-e29d-11eb-9fb7-409f40178717.png)

Thank you!

**Comment by chetachiezikeuzor** [comment]
Oof! Ok, I'll be trying something new with this one. Should be fixed in a bit.

**Comment by chetachiezikeuzor** [comment]
Just fixed the issue with the newest update!
