### ISSUE TITLE
Quick Selection Icon is hidden When Viewing a Document

### ISSUE THREAD

**Issue by cbeier** [chetachiezikeuzor/Yin-and-Yang-Theme#22]
I noticed that in the Obsidian Mobile App, the Quick Selection icon is hidden when a document is displayed.
The Quick Selection can only be opened again after I have switched to another view (e.g. to the Graph View).

I use the last (catalyst) version of Obsidian Module and the Yin and Yang theme.

The quick selection icon is hidden by the document header:
![IMG_0223](https://user-images.githubusercontent.com/53869/125757557-8f0b650e-ebd2-4071-a22f-3e06eae515ca.jpg)

![IMG_0224](https://user-images.githubusercontent.com/53869/125757634-5c3fd294-012b-4bf9-918d-780e98d2f478.jpg)

**Comment by chetachiezikeuzor** [comment]
When did you install the theme? This should be fixed with the latest version 🙂

**Comment by cbeier** [comment]
Some days ago (but I do not remember exactly when).

Doesn't the theme update automatically in Obsidian?

**Comment by chetachiezikeuzor** [comment]
Themes do not automatically update. You will need to reinstall the theme! It will ask you if you'd like to override the correct .css file so just permit it to do so.

**Comment by chetachiezikeuzor** [comment]
Have you updated the theme?

**Comment by chetachiezikeuzor** [comment]
This issue has been fixed! 👍
