### ISSUE TITLE
Icon not centered (mobile)

### ISSUE THREAD

**Issue by Mara-Li** [chetachiezikeuzor/Yin-and-Yang-Theme#23]
![image](https://user-images.githubusercontent.com/30244939/125836411-f10b2cbe-9a3c-423a-add5-c181004ed1d5.png)
The image icon is not placed as the original

![image](https://user-images.githubusercontent.com/30244939/125836501-2998dd38-afe4-4380-80d8-47f1637b77fe.png)

**Comment by chetachiezikeuzor** [comment]
Do you have Alternative Icons toggled on in the first image?

**Comment by chetachiezikeuzor** [comment]
I'm trying out a new icon mapping scheme so give me a couple days and this should be fixed!

**Comment by chetachiezikeuzor** [comment]
I've overhauled all icons so they work better on mobile! This is included in the newest update 👍
