### ISSUE TITLE
Icon for '.org' files resembles archive, but should be a document

### ISSUE THREAD

**Issue by ryanpcmcquen** [chetachiezikeuzor/Yin-and-Yang-Theme#24]
<img width="193" alt="Screen Shot 2021-07-15 at 1 22 17 PM" src="https://user-images.githubusercontent.com/772937/125852515-e05b70bc-e5ab-4531-8fa9-3cae23f4cb15.png">

Lower priority than #21 though.

**Comment by chetachiezikeuzor** [comment]
Is there even a way to detect file type with css in Obsidian? 🐰Into the rabbit hole I go!

**Comment by ryanpcmcquen** [comment]
If there is an attribute that provides the filename you could use wildcard selectors.

**Comment by chetachiezikeuzor** [comment]
How's that? 🤓
<img width="331" alt="Screen Shot 2021-07-18 at 3 10 17 PM" src="https://user-images.githubusercontent.com/79069364/126080878-a27c4b66-eac0-4a2b-aa4d-a25410bd6246.png">

**Comment by ryanpcmcquen** [comment]
Something like this may work:
```[data-path$=".org"]```

**Comment by chetachiezikeuzor** [comment]
Sorry, but I beat you to it!

**Comment by ryanpcmcquen** [comment]
> Sorry, but I beat you to it! I was asking if you liked the icon.

The icon is good!

**Comment by chetachiezikeuzor** [comment]
The newest update includes the icon and many others! 👍
