### ISSUE TITLE
Fenced Code Block on PDF

### ISSUE THREAD

**Issue by valantien** [chetachiezikeuzor/Yin-and-Yang-Theme#26]
First of all thank you for your amazing Theme, i'm fall in love.

Just a little detail, when I used a code block, and export from dark mode to pdf , the font  is unreadable.

eg. 
```markdown
here we can write code.  
or **strong** test
```

![Screen Shot 2021-07-20 at 19 15 52](https://user-images.githubusercontent.com/65976883/126402406-ec6c70fd-b46e-4f1e-8ee9-725e915caa69.png)

thank you.

**Comment by chetachiezikeuzor** [comment]
May I ask when you last installed the theme? Also, is this exported from dark mode?
This may be an issue (https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/issues/15) that has been solved so let me know!

**Comment by chetachiezikeuzor** [comment]
Try updating the theme now and let me know how it exports!
