### ISSUE TITLE
Bug: Scrolling page in preview mode

### ISSUE THREAD

**Issue by EhuddR** [chetachiezikeuzor/Yin-and-Yang-Theme#27]
Hi! First of all the theme is beautifull. Recently I was using the Ying and Yang theme and I realized that it has a rather annoying bug, and that is that when you link a panel in preview mode with another in edit mode it automatically returns.

Here is an example:

https://user-images.githubusercontent.com/78237982/126743129-bab4e3c0-13dc-4dcd-8ab8-945754e2b5cf.mp4

Thank You for the theme

**Comment by chetachiezikeuzor** [comment]
This is the cost of having the custom relationship lines with lists. I could add a setting to remove or de-emphasize them but just know that you won’t be able to have the standard relationship lines native to the theme.

**Comment by chetachiezikeuzor** [comment]
You can now turn off relationship lines in preview mode with the newest update! The setting is under Yin and Tang Theme Minimalize Elements > List Elements.

**Comment by EhuddR** [comment]
Thank you! It's a great feature.
