### ISSUE TITLE
How do I put the top title bar on the left?

### ISSUE THREAD

**Issue by akimolll** [chetachiezikeuzor/Yin-and-Yang-Theme#29]
Hey, thank you for creating such a great theme. It's really beautiful beyond imagination. I try my best to imitate the style in your drawing. Now I encounter a problem. Put the top title bar on one side. I can't do what it looks like in your effect drawing. Does it no longer support this style? Thanks again. ❤️

**Comment by akimolll** [comment]
I found it. It's Sliding Panes. 😘

**Comment by chetachiezikeuzor** [comment]
Lol! Yes, looks like you got it. 🥳
