### ISSUE TITLE
Emojis treated as images

### ISSUE THREAD

**Issue by LaP0573** [chetachiezikeuzor/Yin-and-Yang-Theme#3]
Just noticed the issue with width:100% was solved for emojis (on community version of the theme), however it seems emojis are treated as blocks and trigger a line return after them.

Here it is in editor :
![image](https://user-images.githubusercontent.com/9264791/120204786-7ce8a080-c229-11eb-9ea6-39c8365e63b4.png)

Here it is in preview :
![image](https://user-images.githubusercontent.com/9264791/120204814-84a84500-c229-11eb-813a-cee648f462d0.png)

Maybe emojis should be treated as simple text?

**Comment by chetachiezikeuzor** [comment]
Oof, I guess because I'm on Mac, I really can't see these differences. But yea, I could definitely make that fix!
