### ISSUE TITLE
Two Customization Requests and a Bug

### ISSUE THREAD

**Issue by orionpilot** [chetachiezikeuzor/Yin-and-Yang-Theme#31]
Hi,

Thanks for the great theme, really liking all the customization options. There's two more that I'd like to see added personally: 

- toggle to see the vault title/obsidian version at the top of the screen
- toggle on/off the code block language popup that's in the bottom right hand corner

This is just how I'd like my vault to look but since others may want to keep it like it is, I suggest a toggle to turn them on and off as needed.

For the bug, when rendering a code block in preview, the first line is not aligned properly.

Aligned example from vanilla Obsidian (i.e. no plugins or other themes): 
![image](https://user-images.githubusercontent.com/32915653/128645875-dcf294b7-54f6-4f25-995b-595e50c53eeb.png)

and with the theme:

![image](https://user-images.githubusercontent.com/32915653/128645888-625afc71-68c8-4d1f-b2c8-84d7ffbc7b2a.png)

Arrow points to the misaligned first line. 

It's harder to see but the bug is also visible in #20.

Thanks!

**Comment by kennonb** [comment]
I'll try to do a PR for this when I can, but for the time being if you want to add this custom CSS snippet, it should fix the code misalignment. At least it's working locally for me at the moment. :) 

[fix-code-block-alignment.css.zip](https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/files/6958665/fix-code-block-alignment.css.zip)

**Comment by chetachiezikeuzor** [comment]
I've been working on a huge update to Y&Y for about two weeks now so most of these will already be included in it!

> - toggle to see the vault title/obsidian version at the top of the screen

I'll go ahead and add this one to my updates!

> - toggle on/off the code block language popup that's in the bottom right hand corner

Already have this covered 😉


> For the bug, when rendering a code block in preview, the first line is not aligned properly.

This will also be taken care of! I should be done with everything in a few days. Thanks 😊

**Comment by orionpilot** [comment]
> I'll try to do a PR for this when I can, but for the time being if you want to add this custom CSS snippet, it should fix the code misalignment. At least it's working locally for me at the moment. 😄

The snippet worked for me, thanks! I don't know any css so I didn't realize how simple the fix was 😂

**Comment by chetachiezikeuzor** [comment]
Both of your requests have been added and the bug is fixed. Vault title is shown by default and can be hidden under Yin and Yang Theme > Minimalize Elements > Vault. Then code langue can be hidden under Yin and Yang > Minimalize Elements > Code Blocks. 👌🏽
