### ISSUE TITLE
v1.1.0: Lists in Preview Mode are Left-aligned

### ISSUE THREAD

**Issue by s-kyy** [chetachiezikeuzor/Yin-and-Yang-Theme#33]
Found a bug where only in preview mode lists would be completely left-aligned with the bullets / numbers/ checklist box would be in the gutter. They should instead look indented like in editor mode. 

### Preview Mode
![image](https://user-images.githubusercontent.com/19920083/129220226-03e242c4-d83c-44f1-8854-9320d3274fde.png)
![image](https://user-images.githubusercontent.com/19920083/129220818-1c11516a-f8e9-4696-9c24-d6f08fab18d8.png)

### Editor Mode
![image](https://user-images.githubusercontent.com/19920083/129220268-65ac2b6a-a4e5-49f6-baeb-3514cbb96548.png)
![image](https://user-images.githubusercontent.com/19920083/129220853-6a6c8c1c-dc4e-421d-a6dc-7b9896d7b944.png)

I found the same behaviour whether Outliner plugin or Style Settings plugin were on or off. 

Obsidian Version: v0.12.12
Theme Version: 1.1.0 (no snippets)

**Comment by chetachiezikeuzor** [comment]
They are not left-aligned, this is a problem with Style Settings, unfortunately. The plugin doesn't read the default values right away so you'll have to reset them here. (Yin and Yang Theme > Minimalize Elements > List Elements.

<img width="635" alt="Screen Shot 2021-08-12 at 10 14 39 AM" src="https://user-images.githubusercontent.com/79069364/129222391-f4d01f5b-c842-495d-b87f-56dbb2325271.png">

**Comment by s-kyy** [comment]
Thanks for the quick reply! Completely missed that in settings.

**Comment by chetachiezikeuzor** [comment]
> Thanks for the quick reply! Completely missed that in settings.

I just added a potential fix for it so hopefully, this doesn't happen to anyone else. 🤞🏽
