### ISSUE TITLE
Not compatible with checklist plugin anymore

### ISSUE THREAD

**Issue by shaggyfeng** [chetachiezikeuzor/Yin-and-Yang-Theme#34]
Checklist plugin V1.2.3
![Screenshot (199)](https://user-images.githubusercontent.com/75353922/129317209-922de80e-85c9-4616-a4ae-c35144faca26.png)

Checklist plugin V1.2.2
![Screenshot (200)](https://user-images.githubusercontent.com/75353922/129317248-2f4d982d-29c2-42ee-bb35-e43fb1508146.png)

[Checklist's developer said they did not find what causes this on their end. Maybe you can help.](https://github.com/delashum/obsidian-checklist-plugin/issues/79#issuecomment-898448929)
(https://github.com/delashum/obsidian-checklist-plugin/issues/79#issuecomment-898498169)

**Comment by chetachiezikeuzor** [comment]
Hmm, I don't remember touching the styling for the plugin in a while, but yea it's probably on my end. I'll go ahead and remove all styling for it!

**Comment by chetachiezikeuzor** [comment]
Ok! Should look more like default now.

**Comment by shaggyfeng** [comment]
Thanks, You are the best!

**Comment by chetachiezikeuzor** [comment]
No problem!!
