### ISSUE TITLE
Rendering of heading that contain internal links

### ISSUE THREAD

**Issue by spiritualgeek** [chetachiezikeuzor/Yin-and-Yang-Theme#37]
Something like
`## [[link|This is a title]]`
Will not render correctly in Edit or Preview mode
See the ITS theme for how it should look (But I want to shift to your theme :))

**Comment by chetachiezikeuzor** [comment]
I'm not sure what you mean by "render correctly." It looks like it renders as intended. Could you describe what it is you're getting at?

**Comment by chetachiezikeuzor** [comment]
Okay I think I know what you're saying now. Another user mentioned this to me as well so I'll go ahead and change it, then update you. Thanks!

**Comment by chetachiezikeuzor** [comment]
Hello, very sorry for the late response! I've just added some updates that should address the issue you've raised. Go ahead and reinstall and let me know how the update is working for you. Thanks!

<img width="249" alt="Screen Shot 2021-09-16 at 5 47 18 PM" src="https://user-images.githubusercontent.com/79069364/133695189-a4a255ba-7265-4be1-8e82-407a090bfcc9.png">
