### ISSUE TITLE
[BUG?] Icon change when I change display language

### ISSUE THREAD

**Issue by Quorafind** [chetachiezikeuzor/Yin-and-Yang-Theme#4]
When I change display language from English to zh-CN , the some icons changed.

the pin icon/vault icon in zh-CN
![image](https://user-images.githubusercontent.com/13215013/120569817-425d4e80-c449-11eb-8852-62e8527a1a91.png)

the pin icon/vault icon in EN
![image](https://user-images.githubusercontent.com/13215013/120569840-55701e80-c449-11eb-95d2-4d97a0c2f4cf.png)

**Comment by chetachiezikeuzor** [comment]
This is not a bug, but it is something I'm working on fixing. The icons are set by data that is in English. I'm working on creating an svg sheet that will replace all of Obsidian's default icons. I will then include this in the theme so the icons remain regardless of any language change. I should have this all done by the end of the week. Hope this helps!

**Comment by chetachiezikeuzor** [comment]
I just added this enhancement with the latest update! Sorry for the wait but I hope you enjoy! 

To toggle the enhancement on, go to Style Settings (have the plugin downloaded) > Yin and Yang Theme > More Customization > Alternative Icons. 

🤗
