### ISSUE TITLE
Can’t hide the title bar using plugin “Hider”

### ISSUE THREAD

**Issue by KElee01** [chetachiezikeuzor/Yin-and-Yang-Theme#40]
The left part of the title bar can't be transparent when enabling "MacOS-Like Transparent Window" using the plugin "Style Setting" and enabling"Hide title bar (frameless mode)" using the plugin "Hider".
<img width="335" alt="截屏2021-08-30 下午3 58 14" src="https://user-images.githubusercontent.com/54350573/131306071-891185ca-19a3-4add-956e-97e1515f4910.png">

**Comment by chetachiezikeuzor** [comment]
Very sorry for such a late response! I've just added an update to the theme with some fixes to address the issue you've raised. Please let me know how these changes work for you! Thank you!

<img width="477" alt="Screen Shot 2021-09-16 at 5 40 50 PM" src="https://user-images.githubusercontent.com/79069364/133694674-01ffcac9-d976-45f3-8979-853d87701092.png">
re

**Comment by KElee01** [comment]
It's fixed, thank you!
