### ISSUE TITLE
Mobile side bar like search, when expanding to the full screen it gets cut off

### ISSUE THREAD

**Issue by GitMurf** [chetachiezikeuzor/Yin-and-Yang-Theme#42]
I think maybe just need to either hide the left icons bar when in full screen mode, or shrink the search area/element/view. 

![16D45731-07F7-4814-BEAA-08F2796B1649](https://user-images.githubusercontent.com/64155612/131593361-302a02e1-79de-4010-b5cd-41ac6f614f0c.jpeg)

![F68A9F2E-FDC6-4948-816D-812369AF4609](https://user-images.githubusercontent.com/64155612/131593365-dd0dd1b5-2d51-4558-84a7-86515d81210c.png)

**Comment by chetachiezikeuzor** [comment]
I just added a fix for this. Thanks for the tip Murf! ❤️

**Comment by GitMurf** [comment]
Thanks for taking a look so quickly… but now the full screen mode button is gone. Any clue what happened to it?

![5147FF5C-3DDC-4E93-B2B0-7CCADC202241](https://user-images.githubusercontent.com/64155612/131602822-3a038059-5b09-4a17-b99a-8ee7f0876846.jpeg)

**Comment by chetachiezikeuzor** [comment]
Gah!! Okay, I'll look at it after class today. Thank you!

**Comment by chetachiezikeuzor** [comment]
Okay, should be good to go now. Please let me know how it works out for ya!

**Comment by GitMurf** [comment]
@chetachiezikeuzor omg it is perfect!! Better than I was even hoping :-) thank you!

**Comment by chetachiezikeuzor** [comment]
Yippie! 🥳
