### ISSUE TITLE
Conflict with Typewriter Scroll Plugin

### ISSUE THREAD

**Issue by raisabelatrix** [chetachiezikeuzor/Yin-and-Yang-Theme#43]
So I looove this theme, and I can never use Obsidian without it. But there's just one problem. When I use this theme, the Typewriter Scroll plugin doesn't work. When I switch to a different theme, the plugin works, so I think the problem lies with the Yin and Yang theme.

I really don't want to have to switch themes whenever I'm in focus mode (i.e. using the Typewriter plugin), so I really hope this issue can be fixed..

Edit: The Zen mode in the plugin works... but the typewriter scrolling effect doesn't

**Comment by chetachiezikeuzor** [comment]
Sure! I'll go ahead and take a look at it today to see what's up. Thanks for the tip!

**Comment by chetachiezikeuzor** [comment]
Okay I think I found the issue. Let know If this should be the expected behavior, so I can make the push!


https://user-images.githubusercontent.com/79069364/132100405-5cec7809-2996-4d21-8ad9-455d82add447.mp4

**Comment by raisabelatrix** [comment]
@chetachiezikeuzor yup, that's how it should work!
