### ISSUE TITLE
Minor graphical bug in global graph

### ISSUE THREAD

**Issue by davidedellagiustina** [chetachiezikeuzor/Yin-and-Yang-Theme#46]
![immagine](https://user-images.githubusercontent.com/22601842/132256584-db43d494-28d4-4643-a6d7-686a0c2e4b45.png)

**Comment by chetachiezikeuzor** [comment]
I'm not quite seeing the error here. Could you explain the bug you're experiencing?

**Comment by davidedellagiustina** [comment]
The two buttons are separated by an unclickable area which does nothing. Was it intended..?

**Comment by chetachiezikeuzor** [comment]
<img width="1041" alt="Screen Shot 2021-09-07 at 2 23 11 AM" src="https://user-images.githubusercontent.com/79069364/132302703-cc15c937-a2ba-4e7c-8d76-d72815af0a9b.png">

<img width="1040" alt="Screen Shot 2021-09-07 at 2 24 31 AM" src="https://user-images.githubusercontent.com/79069364/132302748-3cbef2bf-e855-45e8-87d7-de40cb922b09.png">

Not necessarily. It's just a margin value added by the native app css itself. So I wouldn't call it a bug or something I intended. I see it more as a separator between the two buttons.
