### ISSUE TITLE
Single line breaks not showing in preview mode

### ISSUE THREAD

**Issue by raisabelatrix** [chetachiezikeuzor/Yin-and-Yang-Theme#47]
I have the "Strict Line Breaks" option in Obsidian turned off in order to make single line breaks visible. However, the Yin yang theme doesn't respect the setting and still does not show line breaks.

Line breaks in default Obsidian theme:
![image](https://user-images.githubusercontent.com/82343091/132333227-1fb001e5-22ef-4e94-ba1d-a731a8c06916.png)

No line breaks in Yin Yang theme:
![image](https://user-images.githubusercontent.com/82343091/132333292-1d733190-7e47-47d3-9820-496e5a3979bf.png)

**Comment by chetachiezikeuzor** [comment]
This is something I'm currently working on, and should have finished in a few days. Can you send me a screenshot of your markdown file? Or, if you're comfortable, the file itself? 
<img width="944" alt="Screen Shot 2021-09-07 at 8 06 03 AM" src="https://user-images.githubusercontent.com/79069364/132349742-8d170552-c01c-4507-82eb-1b28fd98e853.png">
<img width="944" alt="Screen Shot 2021-09-07 at 8 06 13 AM" src="https://user-images.githubusercontent.com/79069364/132349764-4e4121d1-1c28-4973-a740-0e18000ce4e9.png">

**Comment by raisabelatrix** [comment]
[Writing a Short Story.md](https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/files/7127389/Writing.a.Short.Story.md)

Here ya go

**Comment by chetachiezikeuzor** [comment]
Hello! Apologies for the late response. I've just recently updated the theme and included some tweaks to fix the issue you've addressed. Please let me know how it's working out for you!

**Comment by raisabelatrix** [comment]
Just checked, and everything's fixed now! Thanks so much for your work

**Comment by chetachiezikeuzor** [comment]
Thanks!!! Let me know if anything else comes up, cheers!! ❤️
