### ISSUE TITLE
[BUG?] Text in Kanban card seems weird.

### ISSUE THREAD

**Issue by Quorafind** [chetachiezikeuzor/Yin-and-Yang-Theme#5]
![image](https://user-images.githubusercontent.com/13215013/120570068-d8917480-c449-11eb-9d2e-85a7f9860e62.png)

**Comment by chetachiezikeuzor** [comment]
Yea, sorry about this! I just changed a few things so it should be fixed now. Go ahead and reinstall, let me know if the issue has been solved for you.

**Comment by Quorafind** [comment]
It works well now, thanks!
