### ISSUE TITLE
Which plugins are used in your demos?

### ISSUE THREAD

**Issue by piotryordanov** [chetachiezikeuzor/Yin-and-Yang-Theme#50]
Hey, really cool theme.

I was curious which plugins you are using in the pics?
I recognize `cMenu` and the `alternative file menu`, but what are you using for:
1. Highlighting on a PDF
2. Are the buttons for Menu, typo and color here, from a plugin? 
![image](https://user-images.githubusercontent.com/48773775/132954244-d3477b43-c39d-40ca-aa16-4cb69fc7574f.png)

Thanks in advance!

**Comment by chetachiezikeuzor** [comment]
I'm not sure what you mean by highlighting on pdf but the menu in this screenshot isn't actually a plugin. The buttons you see are from the [Whitehouse gov](https://www.whitehouse.gov) website (which I use sometimes when I take notes) and I'm using the [Search The Internet plugin](https://github.com/HEmile/obsidian-search-on-internet) to get the site in an iframe in its own view. There is a plugin called [Annotator plugin](https://github.com/elias-sundqvist/obsidian-annotator) that allows you to annotate pdfs but I haven't played with it yet so I'm not entirely sure how fully functional it is. Hope this helps!

https://user-images.githubusercontent.com/79069364/132954609-f29f4f7f-3352-4036-ad0a-8f89821f0682.mp4

**Comment by piotryordanov** [comment]
Oh waw, the white house gov website is stylish haha.

For the highlighting I was referring to this:
![image](https://user-images.githubusercontent.com/48773775/132954796-bef0dd2f-b36e-4eb3-b241-4e8a140399b3.png)

**Comment by chetachiezikeuzor** [comment]
Right! So this isn’t highlighting pdf text, but text in the actual note. I’m using my [Highlightr](https://github.com/chetachiezikeuzor/Highlightr-Plugin) plugin for this (this is unreleased btw).

**Comment by piotryordanov** [comment]
Really cool plugin. Can't wait for it to be released!
Any ETA?

**Comment by chetachiezikeuzor** [comment]
Oh, lol I was gonna release it (once upon a time) but sorta kinda gave up on it 😅. I mean it works but I can't imagine it being something many people would be interested in. I did make a [reddit post](https://www.reddit.com/r/ObsidianMD/comments/nu0olr/multicolored_highlighting_in_obsidian/) on how to get a similar result with the Templater plugin.

**Comment by piotryordanov** [comment]
Do release it :)
