### ISSUE TITLE
Can you add other payment channels?

### ISSUE THREAD

**Issue by akimolll** [chetachiezikeuzor/Yin-and-Yang-Theme#55]
I really want to support you through payment, because I have used this theme for several months. When I was paying, I found that buymeacoffee did not support some Chinese bank accounts. I think I'm not the only one who has such an idea, but I was rejected by buymeacoffee. 🥲🥲🥲

**Comment by chetachiezikeuzor** [comment]
Omg, my sincerest apologies! I had no idea this was an issue with buymeacoffee. I’m going to look into it myself but please let me know of an alternative that is more comfortable and works for you 😓.

**Comment by akimolll** [comment]
> Omg, my sincerest apologies! I had no idea this was an issue with buymeacoffee. I’m going to look into it myself but please let me know of an alternative that is more comfortable and works for you 😓.

I think nothing is more convenient than paying directly to a personal account with a QR code. Maybe its payment UI will not be very beautiful, but it is very practical. For example, "PayPal", "Alipay", "wechat pay" and so on.😸
By the way, here is an example: https://github.com/akimolll/Awesome-TTRSS

**Comment by chetachiezikeuzor** [comment]
Hello again! I just added a PayPal link and I will work on adding the others you've mentioned. Thanks so much!

**Comment by akimolll** [comment]
> Hello again! I just added a PayPal link and I will work on adding the others you've mentioned. Thanks so much!

Using PayPal is also a great choice. It also provides services in China and is very popular. Thank you again for your theme and efforts. I will always support your work. thank you.❤️❤️❤️

**Comment by chetachiezikeuzor** [comment]
Thank you so much for your generosity!! I'm just glad that you like the theme! 🤗 Please let me know of any changes I could make to make it even better.
