### ISSUE TITLE
Collapse Indicator

### ISSUE THREAD

**Issue by phlind** [chetachiezikeuzor/Yin-and-Yang-Theme#57]
When I deactivate the custom icons in the style settings, the collapse indicator doesn't seem right:

![Unbenannt](https://user-images.githubusercontent.com/30386310/133933201-73dd078a-1b12-4194-887d-21b24b697a5d.PNG)

**Comment by chetachiezikeuzor** [comment]
Sorry about that! I just pushed a fix for it so let me know how it works!

**Comment by phlind** [comment]
Works fine now, thanks for the fast fix! :)

**Comment by chetachiezikeuzor** [comment]
No problemo! 😊
