### ISSUE TITLE
Highlight colour on file rename

### ISSUE THREAD

**Issue by bilal-khan** [chetachiezikeuzor/Yin-and-Yang-Theme#58]
Hi, firstly thank you for making this theme - it's my favourite one by far!! Just stunning.

I'm noticing an issue on file rename. The highlight is white, which makes it very difficult to see against the background.

Reproduce:
- Right click on file in left sidebar
- Choose to rename

<img width="402" alt="Screenshot 2021-09-20 at 09 27 32" src="https://user-images.githubusercontent.com/1732656/133975560-837fa38a-b95f-44b2-86ea-0f269584a595.png">

**Comment by chetachiezikeuzor** [comment]
Ok, I just updated the theme and it should be a normal color. Please let me know if the solution is sufficient 😊.
