### ISSUE TITLE
Sidebar Icons Missing

### ISSUE THREAD

**Issue by ithinkiamjoseph** [chetachiezikeuzor/Yin-and-Yang-Theme#60]
I'm obsessed with your theme, but for some reason mine looks sightly different than yours. All my sidebar icons are missing. I'll post a screenshot. I don't have any snippets activated either. And it doesn't seem that any plugin has done that. 
<img width="1792" alt="Screen Shot 2021-09-26 at 7 25 45 PM" src="https://user-images.githubusercontent.com/4108750/134827881-46517358-34ea-46fb-b39f-fb67f6e1adbf.png">

**Comment by chetachiezikeuzor** [comment]
Woah, yea this looks completely different. Actually it kinda looks like a super old version of the theme. Can I ask when you last installed it?

**Comment by chetachiezikeuzor** [comment]
Wait that can’t be it. Now I’m really confused. I can’t figure out why yours is looking so different.

**Comment by chetachiezikeuzor** [comment]
Okay, could you try sending me the raw css file? And what OS are you on?

**Comment by ithinkiamjoseph** [comment]
Let me send the raw CSS real quick.

**Comment by ithinkiamjoseph** [comment]
Here it is in a txt file:
[Yin and Yang.txt](https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/files/7232545/Yin.and.Yang.txt)

**Comment by chetachiezikeuzor** [comment]
Thank you very much! I'll do some sleuthing for the time being. Could you try the theme on a brand new vault?

**Comment by ithinkiamjoseph** [comment]
Works on a new vault. So likely something weird on my end. I'll see what I can do.

**Comment by chetachiezikeuzor** [comment]
OK, well that's just super weird! Perhaps there's an issue with the YAML in the theme, maybe it's conflicting with something else that uses Style Settings. Idk. What plugins do you have?

**Comment by ithinkiamjoseph** [comment]
Well, not it's working. I went back into my main vault, disabled all my plugins, reloaded my themes, quit Obsidian and restarted. Now it's working. Oh well. Now it looks awesome! Thanks!
