### ISSUE TITLE
Enhancement : Add style settings for background color

### ISSUE THREAD

**Issue by Mara-Li** [chetachiezikeuzor/Yin-and-Yang-Theme#7]
Hey !
I saw you use HSL for the background, and I think it can be cool to add some style settings support to change it a little. I think the variable number slider (or variable number) can be useful for that. 
Also, it will be good to add specific color for each background primary and secondary or adding a variable for the last `+ x%`.
Something like : 
```--background-secondary:hsl(var(--base-h), var(--base-s), calc(var(--base-d) + var(--base-secondary))```
And same for primary and tertiary.

I think it can be a good improvement and addition to the other customization!

**Comment by chetachiezikeuzor** [comment]
You are so awesome! This is exactly what I was thinking of 😆 I do want to get some other things out of the way with the theme first then get started on this implementation, so I'll keep you posted!

**Comment by chetachiezikeuzor** [comment]
It's been long awaited but the enhancement has been added! Thank you for your patience 🤗

**Comment by piotryordanov** [comment]
Hey @chetachiezikeuzor I'm unable to find this option in the settings.
Is that an option that allows me to make the editor background, for example, yellow or green?

Cheers and thx for the awesome theme!

**Comment by chetachiezikeuzor** [comment]
@piotryordanov The enhancement requires for you to have the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings) installed. There, you should see the theme title "Yin and Yang Theme," and then you will see a section that says "Base Color Change." From there, you will be able to change the base hue and saturation. I'll be adding another setting for base darkness, to customize the darkness level in dark mode, so stay tuned for that!

**Comment by piotryordanov** [comment]
@chetachiezikeuzor I am using the plugin already.

I was hoping I can change the color of the editor. In light mode it's always white when i'd have preferred some sepia flavour.
Is that possible?

**Comment by chetachiezikeuzor** [comment]
The background color is set by multiple hsl value splitting, so it isn't easy to have this customizable without compromising the theme. But you can change the color with a css snippet if you'd like. The background in editor is set by the variable `background-primary` so changing the value of this should suffice.

```css
.theme-light{
--background-primary: #f7eee5;
}

.theme-dark{
--background-primary: #704214;
}
```

To have the new value only effect the note:

```css
.theme-light .workspace-split.mod-root{
--background-primary: #f7eee5;
}

.theme-dark .workspace-split.mod-root{
--background-primary: #704214;
}
```

Let me know how this works for you!

**Comment by piotryordanov** [comment]
That would pretty much do the job for me.

However, what do I need to do for the sidebars to also get the background? 
Right now, only the note is taking the color: 
![image](https://user-images.githubusercontent.com/48773775/133251280-d80be327-42ce-4466-87a1-961974272098.png)
