### ISSUE TITLE
[bug] All text disappears when using ctrl + f in legacy editor

### ISSUE THREAD

**Issue by youcefs21** [chetachiezikeuzor/Yin-and-Yang-Theme#82]
when I try to search my note using ctrl + f in the legacy editor, all the text in my note disappears, as can be seen in the gif below:
![searchBug](https://user-images.githubusercontent.com/34604972/147859444-f2453d98-02e5-4edf-b55f-9fe38f0955a5.gif)

I've traced this bug down to this theme as it occurs even with all my plugins disabled, however, when I switch themes, it works as intended:
![searchWorking](https://user-images.githubusercontent.com/34604972/147859565-495a547d-736e-4814-b286-78aa34bb1848.gif)

everything works as intended when using the non-legacy editor, even when in source editing mode

**Comment by chetachiezikeuzor** [comment]
Hello! I have just added a fix for this, please let me know if it works for you! Thanks! 😊

**Comment by youcefs21** [comment]
works great, thanks a lot!
