### ISSUE TITLE
Cannot see cursor in tables in normal vim mode.

### ISSUE THREAD

**Issue by krusse** [chetachiezikeuzor/Yin-and-Yang-Theme#9]
The cursor disappears when navigating through a table making it impossible to edit unless going into insert mode and clicking.

Cursor right below:
![image](https://user-images.githubusercontent.com/6863901/121403025-801a1580-c928-11eb-89cf-8344dda7d308.png)

Cursor 1 line up:
![image](https://user-images.githubusercontent.com/6863901/121403125-9cb64d80-c928-11eb-886f-af660d0272bf.png)

**Comment by chetachiezikeuzor** [comment]
When did you last update the theme? I've since made changes to tables and I believe that should solve this issue. I don't use vim mode though so keep that in mind. 🙂

**Comment by krusse** [comment]
Yes, it is fixed. 

I feel like I just started using the theme yesterday. Do you ever work fast!

Thanks.

**Comment by chetachiezikeuzor** [comment]
Lol, I'm a bit of a crazy person so I update things all the time. I'll definitely look into getting some sort of theme announcement going. And no problemo! :)
